/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLHackeoUrbanoAPIRouteStatsResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   API for Hackeo Urbano (hackeoUrbanoAPI/v1)
// Description:
//   This is the API used by Hackeo Urbano
// Classes:
//   GTLHackeoUrbanoAPIRouteStatsResponse (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLHackeoUrbanoAPIRouteStatsWrapper;

// ----------------------------------------------------------------------------
//
//   GTLHackeoUrbanoAPIRouteStatsResponse
//

// This class supports NSFastEnumeration over its "items" property. It also
// supports -itemAtIndex: to retrieve individual objects from "items".

@interface GTLHackeoUrbanoAPIRouteStatsResponse : GTLCollectionObject
@property (nonatomic, copy) NSString *cursor;
@property (nonatomic, retain) NSArray *items;  // of GTLHackeoUrbanoAPIRouteStatsWrapper
@end
