/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLHackeoUrbanoAPIQuestionnaireWrapper.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   API for Hackeo Urbano (hackeoUrbanoAPI/v1)
// Description:
//   This is the API used by Hackeo Urbano
// Classes:
//   GTLHackeoUrbanoAPIQuestionnaireWrapper (0 custom class methods, 9 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLHackeoUrbanoAPIQuestionnaireWrapper
//

@interface GTLHackeoUrbanoAPIQuestionnaireWrapper : GTLObject
@property (nonatomic, retain) NSNumber *fullness;  // intValue
@property (nonatomic, copy) NSString *notes;
@property (nonatomic, retain) NSNumber *rating;  // intValue
@property (nonatomic, retain) NSArray *security;  // of NSNumber (intValue)
@property (nonatomic, retain) NSArray *state;  // of NSNumber (intValue)
@property (nonatomic, retain) GTLDateTime *timeTaken;
@property (nonatomic, retain) NSNumber *trailId;  // longLongValue
@property (nonatomic, retain) NSArray *transitRegulation;  // of NSNumber (intValue)
@property (nonatomic, retain) NSNumber *transportType;  // intValue
@end
