/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLHackeoUrbanoAPIRouteStatsWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   API for Hackeo Urbano (hackeoUrbanoAPI/v1)
// Description:
//   This is the API used by Hackeo Urbano
// Classes:
//   GTLHackeoUrbanoAPIRouteStatsWrapper (0 custom class methods, 4 custom properties)

#import "GTLHackeoUrbanoAPIRouteStatsWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLHackeoUrbanoAPIRouteStatsWrapper
//

@implementation GTLHackeoUrbanoAPIRouteStatsWrapper
@dynamic destinyStation, identifier, originStation, rating;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
