/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLHackeoUrbanoAPIRouteStatsParameter.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   API for Hackeo Urbano (hackeoUrbanoAPI/v1)
// Description:
//   This is the API used by Hackeo Urbano
// Classes:
//   GTLHackeoUrbanoAPIRouteStatsParameter (0 custom class methods, 3 custom properties)

#import "GTLHackeoUrbanoAPIRouteStatsParameter.h"

// ----------------------------------------------------------------------------
//
//   GTLHackeoUrbanoAPIRouteStatsParameter
//

@implementation GTLHackeoUrbanoAPIRouteStatsParameter
@dynamic cursor, descending, numberOfElements;
@end
