/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLHackeoUrbanoAPIQuestionnaireWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   API for Hackeo Urbano (hackeoUrbanoAPI/v1)
// Description:
//   This is the API used by Hackeo Urbano
// Classes:
//   GTLHackeoUrbanoAPIQuestionnaireWrapper (0 custom class methods, 9 custom properties)

#import "GTLHackeoUrbanoAPIQuestionnaireWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLHackeoUrbanoAPIQuestionnaireWrapper
//

@implementation GTLHackeoUrbanoAPIQuestionnaireWrapper
@dynamic fullness, notes, rating, security, state, timeTaken, trailId,
         transitRegulation, transportType;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"security" : [NSNumber class],
    @"state" : [NSNumber class],
    @"transitRegulation" : [NSNumber class]
  };
  return map;
}

@end
