/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLHackeoUrbanoAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   API for Hackeo Urbano (hackeoUrbanoAPI/v1)
// Description:
//   This is the API used by Hackeo Urbano

#import "GTLHackeoUrbanoAPIConstants.h"

#import "GTLHackeoUrbanoAPIQuestionnaireWrapper.h"
#import "GTLHackeoUrbanoAPIRouteStatsParameter.h"
#import "GTLHackeoUrbanoAPIRouteStatsResponse.h"
#import "GTLHackeoUrbanoAPIRouteStatsWrapper.h"

#import "GTLQueryHackeoUrbanoAPI.h"
#import "GTLServiceHackeoUrbanoAPI.h"
