/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLHackeoUrbanoAPIRouteStatsResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   API for Hackeo Urbano (hackeoUrbanoAPI/v1)
// Description:
//   This is the API used by Hackeo Urbano
// Classes:
//   GTLHackeoUrbanoAPIRouteStatsResponse (0 custom class methods, 2 custom properties)

#import "GTLHackeoUrbanoAPIRouteStatsResponse.h"

#import "GTLHackeoUrbanoAPIRouteStatsWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLHackeoUrbanoAPIRouteStatsResponse
//

@implementation GTLHackeoUrbanoAPIRouteStatsResponse
@dynamic cursor, items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLHackeoUrbanoAPIRouteStatsWrapper class]
  };
  return map;
}

@end
