/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLHackeoUrbanoAPIConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   API for Hackeo Urbano (hackeoUrbanoAPI/v1)
// Description:
//   This is the API used by Hackeo Urbano

#import "GTLHackeoUrbanoAPIConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeHackeoUrbanoAPIUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
