/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryHackeoUrbanoAPI.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   API for Hackeo Urbano (hackeoUrbanoAPI/v1)
// Description:
//   This is the API used by Hackeo Urbano
// Classes:
//   GTLQueryHackeoUrbanoAPI (4 custom class methods, 3 custom properties)

#import "GTLQueryHackeoUrbanoAPI.h"

#import "GTLHackeoUrbanoAPIQuestionnaireWrapper.h"
#import "GTLHackeoUrbanoAPIRouteStatsParameter.h"
#import "GTLHackeoUrbanoAPIRouteStatsResponse.h"
#import "GTLHackeoUrbanoAPIRouteStatsWrapper.h"

@implementation GTLQueryHackeoUrbanoAPI

@dynamic fields, identifier, trailId;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

#pragma mark - Service level methods
// These create a GTLQueryHackeoUrbanoAPI object.

+ (instancetype)queryForGetAllStatsWithObject:(GTLHackeoUrbanoAPIRouteStatsParameter *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"hackeoUrbanoAPI.getAllStats";
  GTLQueryHackeoUrbanoAPI *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLHackeoUrbanoAPIRouteStatsResponse class];
  return query;
}

+ (instancetype)queryForGetQuestionnaireWithIdentifier:(long long)identifier {
  NSString *methodName = @"hackeoUrbanoAPI.getQuestionnaire";
  GTLQueryHackeoUrbanoAPI *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.expectedObjectClass = [GTLHackeoUrbanoAPIQuestionnaireWrapper class];
  return query;
}

+ (instancetype)queryForGetStatsWithTrailId:(long long)trailId {
  NSString *methodName = @"hackeoUrbanoAPI.getStats";
  GTLQueryHackeoUrbanoAPI *query = [self queryWithMethodName:methodName];
  query.trailId = trailId;
  query.expectedObjectClass = [GTLHackeoUrbanoAPIRouteStatsWrapper class];
  return query;
}

+ (instancetype)queryForRegisterQuestionnaireWithObject:(GTLHackeoUrbanoAPIQuestionnaireWrapper *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"hackeoUrbanoAPI.registerQuestionnaire";
  GTLQueryHackeoUrbanoAPI *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

@end
