/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryHackeoUrbanoAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   API for Hackeo Urbano (hackeoUrbanoAPI/v1)
// Description:
//   This is the API used by Hackeo Urbano
// Classes:
//   GTLQueryHackeoUrbanoAPI (4 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLHackeoUrbanoAPIQuestionnaireWrapper;
@class GTLHackeoUrbanoAPIRouteStatsParameter;

@interface GTLQueryHackeoUrbanoAPI : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, assign) long long identifier;
@property (nonatomic, assign) long long trailId;

#pragma mark - Service level methods
// These create a GTLQueryHackeoUrbanoAPI object.

// Method: hackeoUrbanoAPI.getAllStats
//  Authorization scope(s):
//   kGTLAuthScopeHackeoUrbanoAPIUserinfoEmail
// Fetches a GTLHackeoUrbanoAPIRouteStatsResponse.
+ (instancetype)queryForGetAllStatsWithObject:(GTLHackeoUrbanoAPIRouteStatsParameter *)object;

// Method: hackeoUrbanoAPI.getQuestionnaire
//  Authorization scope(s):
//   kGTLAuthScopeHackeoUrbanoAPIUserinfoEmail
// Fetches a GTLHackeoUrbanoAPIQuestionnaireWrapper.
+ (instancetype)queryForGetQuestionnaireWithIdentifier:(long long)identifier;

// Method: hackeoUrbanoAPI.getStats
//  Authorization scope(s):
//   kGTLAuthScopeHackeoUrbanoAPIUserinfoEmail
// Fetches a GTLHackeoUrbanoAPIRouteStatsWrapper.
+ (instancetype)queryForGetStatsWithTrailId:(long long)trailId;

// Method: hackeoUrbanoAPI.registerQuestionnaire
//  Authorization scope(s):
//   kGTLAuthScopeHackeoUrbanoAPIUserinfoEmail
+ (instancetype)queryForRegisterQuestionnaireWithObject:(GTLHackeoUrbanoAPIQuestionnaireWrapper *)object;

@end
