/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPISearchByKeywordParameter.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPISearchByKeywordParameter (0 custom class methods, 2 custom properties)

#import "GTLMapatonPublicAPISearchByKeywordParameter.h"

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPISearchByKeywordParameter
//

@implementation GTLMapatonPublicAPISearchByKeywordParameter
@dynamic keyword, numberOfResults;
@end
