/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPITime.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPITime (0 custom class methods, 3 custom properties)

#import "GTLMapatonPublicAPITime.h"

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPITime
//

@implementation GTLMapatonPublicAPITime
@dynamic hour, minute, second;
@end
