/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPIConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton

#import "GTLMapatonPublicAPIConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeMapatonPublicAPIUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
