/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPIAreaWrapper.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPIAreaWrapper (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLMapatonPublicAPIGPSLocation;

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPIAreaWrapper
//

@interface GTLMapatonPublicAPIAreaWrapper : GTLObject
@property (nonatomic, retain) GTLMapatonPublicAPIGPSLocation *northEastCorner;
@property (nonatomic, retain) GTLMapatonPublicAPIGPSLocation *southWestCorner;
@end
