/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPITrailPointWrapper.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPITrailPointWrapper (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLMapatonPublicAPIGPSLocation;
@class GTLMapatonPublicAPITimeStamp;

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPITrailPointWrapper
//

@interface GTLMapatonPublicAPITrailPointWrapper : GTLObject
@property (nonatomic, retain) GTLMapatonPublicAPIGPSLocation *location;
@property (nonatomic, retain) NSNumber *position;  // intValue
@property (nonatomic, retain) GTLMapatonPublicAPITimeStamp *timeStamp;
@end
