/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPIAreaWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPIAreaWrapper (0 custom class methods, 2 custom properties)

#import "GTLMapatonPublicAPIAreaWrapper.h"

#import "GTLMapatonPublicAPIGPSLocation.h"

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPIAreaWrapper
//

@implementation GTLMapatonPublicAPIAreaWrapper
@dynamic northEastCorner, southWestCorner;
@end
