/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPITrailDetails.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPITrailDetails (0 custom class methods, 24 custom properties)

#import "GTLMapatonPublicAPITrailDetails.h"

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPITrailDetails
//

@implementation GTLMapatonPublicAPITrailDetails
@dynamic branchId, branchName, creationDate, destinationPlatformId,
         destinationPlatformName, destinationStationId, destinationStationName,
         gtfsStatus, invalidReason, maxTariff, notes, originPlatformId,
         originPlatformName, originStationId, originStationName, photoUrl,
         routeId, routeName, schedule, totalMeters, totalMinutes, trailId,
         trailStatus, transportType;
@end
