/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPITrailPointsResult.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPITrailPointsResult (0 custom class methods, 2 custom properties)

#import "GTLMapatonPublicAPITrailPointsResult.h"

#import "GTLMapatonPublicAPITrailPointWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPITrailPointsResult
//

@implementation GTLMapatonPublicAPITrailPointsResult
@dynamic cursor, points;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"points" : [GTLMapatonPublicAPITrailPointWrapper class]
  };
  return map;
}

@end
