/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPICursorParameter.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPICursorParameter (0 custom class methods, 2 custom properties)

#import "GTLMapatonPublicAPICursorParameter.h"

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPICursorParameter
//

@implementation GTLMapatonPublicAPICursorParameter
@dynamic cursor, numberOfElements;
@end
