/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPITrailPointsRequestParameter.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPITrailPointsRequestParameter (0 custom class methods, 3 custom properties)

#import "GTLMapatonPublicAPITrailPointsRequestParameter.h"

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPITrailPointsRequestParameter
//

@implementation GTLMapatonPublicAPITrailPointsRequestParameter
@dynamic cursor, numberOfElements, trailId;
@end
