/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPINearTrailsCollection.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPINearTrailsCollection (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLMapatonPublicAPINearTrails;

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPINearTrailsCollection
//

// This class supports NSFastEnumeration over its "items" property. It also
// supports -itemAtIndex: to retrieve individual objects from "items".

@interface GTLMapatonPublicAPINearTrailsCollection : GTLCollectionObject
@property (nonatomic, retain) NSArray *items;  // of GTLMapatonPublicAPINearTrails
@end
