/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPINearTrails.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPINearTrails (0 custom class methods, 4 custom properties)

#import "GTLMapatonPublicAPINearTrails.h"

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPINearTrails
//

@implementation GTLMapatonPublicAPINearTrails
@dynamic branchName, destinationName, originName, trailId;
@end
