/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPITrailDetails.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPITrailDetails (0 custom class methods, 24 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPITrailDetails
//

@interface GTLMapatonPublicAPITrailDetails : GTLObject
@property (nonatomic, retain) NSNumber *branchId;  // longLongValue
@property (nonatomic, copy) NSString *branchName;
@property (nonatomic, retain) GTLDateTime *creationDate;
@property (nonatomic, retain) NSNumber *destinationPlatformId;  // longLongValue
@property (nonatomic, copy) NSString *destinationPlatformName;
@property (nonatomic, retain) NSNumber *destinationStationId;  // longLongValue
@property (nonatomic, copy) NSString *destinationStationName;
@property (nonatomic, retain) NSNumber *gtfsStatus;  // intValue
@property (nonatomic, copy) NSString *invalidReason;
@property (nonatomic, retain) NSNumber *maxTariff;  // doubleValue
@property (nonatomic, copy) NSString *notes;
@property (nonatomic, retain) NSNumber *originPlatformId;  // longLongValue
@property (nonatomic, copy) NSString *originPlatformName;
@property (nonatomic, retain) NSNumber *originStationId;  // longLongValue
@property (nonatomic, copy) NSString *originStationName;
@property (nonatomic, copy) NSString *photoUrl;
@property (nonatomic, retain) NSNumber *routeId;  // longLongValue
@property (nonatomic, copy) NSString *routeName;
@property (nonatomic, copy) NSString *schedule;
@property (nonatomic, retain) NSNumber *totalMeters;  // doubleValue
@property (nonatomic, retain) NSNumber *totalMinutes;  // doubleValue
@property (nonatomic, retain) NSNumber *trailId;  // longLongValue
@property (nonatomic, retain) NSNumber *trailStatus;  // intValue
@property (nonatomic, copy) NSString *transportType;
@end
