/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPITrailDetailsCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPITrailDetailsCollection (0 custom class methods, 1 custom properties)

#import "GTLMapatonPublicAPITrailDetailsCollection.h"

#import "GTLMapatonPublicAPITrailDetails.h"

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPITrailDetailsCollection
//

@implementation GTLMapatonPublicAPITrailDetailsCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLMapatonPublicAPITrailDetails class]
  };
  return map;
}

@end
