/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPITrailPointWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPITrailPointWrapper (0 custom class methods, 3 custom properties)

#import "GTLMapatonPublicAPITrailPointWrapper.h"

#import "GTLMapatonPublicAPIGPSLocation.h"
#import "GTLMapatonPublicAPITimeStamp.h"

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPITrailPointWrapper
//

@implementation GTLMapatonPublicAPITrailPointWrapper
@dynamic location, position, timeStamp;
@end
