/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPIGPSLocation.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPIGPSLocation (0 custom class methods, 3 custom properties)

#import "GTLMapatonPublicAPIGPSLocation.h"

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPIGPSLocation
//

@implementation GTLMapatonPublicAPIGPSLocation
@dynamic latitude, longitude, radius;
@end
