/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPITrailListResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPITrailListResponse (0 custom class methods, 2 custom properties)

#import "GTLMapatonPublicAPITrailListResponse.h"

#import "GTLMapatonPublicAPITrailDetails.h"

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPITrailListResponse
//

@implementation GTLMapatonPublicAPITrailListResponse
@dynamic cursor, trails;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"trails" : [GTLMapatonPublicAPITrailDetails class]
  };
  return map;
}

@end
