/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton

#import "GTLMapatonPublicAPIConstants.h"

#import "GTLMapatonPublicAPIAreaWrapper.h"
#import "GTLMapatonPublicAPICursorParameter.h"
#import "GTLMapatonPublicAPIDate.h"
#import "GTLMapatonPublicAPIGPSLocation.h"
#import "GTLMapatonPublicAPINearTrails.h"
#import "GTLMapatonPublicAPINearTrailsCollection.h"
#import "GTLMapatonPublicAPISearchByKeywordParameter.h"
#import "GTLMapatonPublicAPITime.h"
#import "GTLMapatonPublicAPITimeStamp.h"
#import "GTLMapatonPublicAPITrailDetails.h"
#import "GTLMapatonPublicAPITrailDetailsCollection.h"
#import "GTLMapatonPublicAPITrailListResponse.h"
#import "GTLMapatonPublicAPITrailPointsRequestParameter.h"
#import "GTLMapatonPublicAPITrailPointsResult.h"
#import "GTLMapatonPublicAPITrailPointWrapper.h"

#import "GTLQueryMapatonPublicAPI.h"
#import "GTLServiceMapatonPublicAPI.h"
