/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMapatonPublicAPIDate.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLMapatonPublicAPIDate (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLMapatonPublicAPIDate
//

@interface GTLMapatonPublicAPIDate : GTLObject
@property (nonatomic, retain) NSNumber *day;  // intValue
@property (nonatomic, retain) NSNumber *month;  // intValue
@property (nonatomic, retain) NSNumber *year;  // intValue
@end
