/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryMapatonPublicAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Mapaton Public API (mapatonPublicAPI/v1)
// Description:
//   This is the public API for mapaton
// Classes:
//   GTLQueryMapatonPublicAPI (10 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLMapatonPublicAPIAreaWrapper;
@class GTLMapatonPublicAPICursorParameter;
@class GTLMapatonPublicAPISearchByKeywordParameter;
@class GTLMapatonPublicAPITrailPointsRequestParameter;

@interface GTLQueryMapatonPublicAPI : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *password;
@property (nonatomic, assign) long long trailId;
@property (nonatomic, copy) NSString *trailIds;

#pragma mark - Service level methods
// These create a GTLQueryMapatonPublicAPI object.

// Method: mapatonPublicAPI.getAllGtfsTrails
//  Authorization scope(s):
//   kGTLAuthScopeMapatonPublicAPIUserinfoEmail
// Fetches a GTLMapatonPublicAPITrailListResponse.
+ (instancetype)queryForGetAllGtfsTrailsWithObject:(GTLMapatonPublicAPICursorParameter *)object;

// Method: mapatonPublicAPI.getAllTrails
//  Authorization scope(s):
//   kGTLAuthScopeMapatonPublicAPIUserinfoEmail
// Fetches a GTLMapatonPublicAPITrailListResponse.
+ (instancetype)queryForGetAllTrailsWithObject:(GTLMapatonPublicAPICursorParameter *)object;

// Method: mapatonPublicAPI.getAllValidTrails
//  Authorization scope(s):
//   kGTLAuthScopeMapatonPublicAPIUserinfoEmail
// Fetches a GTLMapatonPublicAPITrailListResponse.
+ (instancetype)queryForGetAllValidTrailsWithObject:(GTLMapatonPublicAPICursorParameter *)object;

// Method: mapatonPublicAPI.getTrailDetails
//  Authorization scope(s):
//   kGTLAuthScopeMapatonPublicAPIUserinfoEmail
// Fetches a GTLMapatonPublicAPITrailDetails.
+ (instancetype)queryForGetTrailDetailsWithTrailId:(long long)trailId;

// Method: mapatonPublicAPI.getTrailRawPoints
//  Authorization scope(s):
//   kGTLAuthScopeMapatonPublicAPIUserinfoEmail
// Fetches a GTLMapatonPublicAPITrailPointsResult.
+ (instancetype)queryForGetTrailRawPointsWithObject:(GTLMapatonPublicAPITrailPointsRequestParameter *)object;

// Method: mapatonPublicAPI.getTrailsByStationName
//  Authorization scope(s):
//   kGTLAuthScopeMapatonPublicAPIUserinfoEmail
// Fetches a GTLMapatonPublicAPITrailDetailsCollection.
+ (instancetype)queryForGetTrailsByStationNameWithObject:(GTLMapatonPublicAPISearchByKeywordParameter *)object;

// Method: mapatonPublicAPI.getTrailSnappedPoints
//  Authorization scope(s):
//   kGTLAuthScopeMapatonPublicAPIUserinfoEmail
// Fetches a GTLMapatonPublicAPITrailPointsResult.
+ (instancetype)queryForGetTrailSnappedPointsWithObject:(GTLMapatonPublicAPITrailPointsRequestParameter *)object;

// Method: mapatonPublicAPI.registerGtfsFullTask
//  Authorization scope(s):
//   kGTLAuthScopeMapatonPublicAPIUserinfoEmail
+ (instancetype)queryForRegisterGtfsFullTaskWithPassword:(NSString *)password;

// Method: mapatonPublicAPI.registerGtfsTask
//  Authorization scope(s):
//   kGTLAuthScopeMapatonPublicAPIUserinfoEmail
+ (instancetype)queryForRegisterGtfsTaskWithPassword:(NSString *)password
                                            trailIds:(NSString *)trailIds;

// Method: mapatonPublicAPI.trailsNearPoint
//  Authorization scope(s):
//   kGTLAuthScopeMapatonPublicAPIUserinfoEmail
// Fetches a GTLMapatonPublicAPINearTrailsCollection.
+ (instancetype)queryForTrailsNearPointWithObject:(GTLMapatonPublicAPIAreaWrapper *)object;

@end
