/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPITrailPointWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPITrailPointWrapper (0 custom class methods, 3 custom properties)

#import "GTLDashboardAPITrailPointWrapper.h"

#import "GTLDashboardAPIGPSLocation.h"
#import "GTLDashboardAPITimeStamp.h"

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPITrailPointWrapper
//

@implementation GTLDashboardAPITrailPointWrapper
@dynamic location, position, timeStamp;
@end
