/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPISearchByKeywordParameter.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPISearchByKeywordParameter (0 custom class methods, 2 custom properties)

#import "GTLDashboardAPISearchByKeywordParameter.h"

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPISearchByKeywordParameter
//

@implementation GTLDashboardAPISearchByKeywordParameter
@dynamic keyword, numberOfResults;
@end
