/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPICursorParameter.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPICursorParameter (0 custom class methods, 2 custom properties)

#import "GTLDashboardAPICursorParameter.h"

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPICursorParameter
//

@implementation GTLDashboardAPICursorParameter
@dynamic cursor, numberOfElements;
@end
