/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton

#import "GTLDashboardAPIConstants.h"

#import "GTLDashboardAPIAreaWrapper.h"
#import "GTLDashboardAPICursorParameter.h"
#import "GTLDashboardAPIDate.h"
#import "GTLDashboardAPIGPSLocation.h"
#import "GTLDashboardAPISearchByKeywordParameter.h"
#import "GTLDashboardAPITime.h"
#import "GTLDashboardAPITimeStamp.h"
#import "GTLDashboardAPITrailDetails.h"
#import "GTLDashboardAPITrailDetailsCollection.h"
#import "GTLDashboardAPITrailListResponse.h"
#import "GTLDashboardAPITrailPointsRequestParameter.h"
#import "GTLDashboardAPITrailPointsResult.h"
#import "GTLDashboardAPITrailPointWrapper.h"

#import "GTLQueryDashboardAPI.h"
#import "GTLServiceDashboardAPI.h"
