/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPIRouteStatsWrapper.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPIRouteStatsWrapper (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPIRouteStatsWrapper
//

@interface GTLDashboardAPIRouteStatsWrapper : GTLObject
@property (nonatomic, copy) NSString *destinyStation;
@property (nonatomic, copy) NSString *originStation;
@property (nonatomic, retain) NSNumber *rating;  // floatValue
@end
