/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPITimeStamp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPITimeStamp (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLDashboardAPIDate;
@class GTLDashboardAPITime;

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPITimeStamp
//

@interface GTLDashboardAPITimeStamp : GTLObject
@property (retain) GTLDashboardAPIDate *date;
@property (retain) GTLDashboardAPITime *time;
@end
