/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPIDate.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPIDate (0 custom class methods, 3 custom properties)

#import "GTLDashboardAPIDate.h"

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPIDate
//

@implementation GTLDashboardAPIDate
@dynamic day, month, year;
@end
