/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPITrailDetails.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPITrailDetails (0 custom class methods, 24 custom properties)

#import "GTLDashboardAPITrailDetails.h"

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPITrailDetails
//

@implementation GTLDashboardAPITrailDetails
@dynamic branchId, branchName, creationDate, destinationPlatformId,
         destinationPlatformName, destinationStationId, destinationStationName,
         gtfsStatus, invalidReason, maxTariff, notes, originPlatformId,
         originPlatformName, originStationId, originStationName, photoUrl,
         routeId, routeName, schedule, totalMeters, totalMinutes, trailId,
         trailStatus, transportType;
@end
