/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPIRouteStatsResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPIRouteStatsResponse (0 custom class methods, 2 custom properties)

#import "GTLDashboardAPIRouteStatsResponse.h"

#import "GTLDashboardAPIRouteStatsWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPIRouteStatsResponse
//

@implementation GTLDashboardAPIRouteStatsResponse
@dynamic cursor, items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLDashboardAPIRouteStatsWrapper class]
  };
  return map;
}

@end
