/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPIRouteStatsWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPIRouteStatsWrapper (0 custom class methods, 3 custom properties)

#import "GTLDashboardAPIRouteStatsWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPIRouteStatsWrapper
//

@implementation GTLDashboardAPIRouteStatsWrapper
@dynamic destinyStation, originStation, rating;
@end
