/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPIConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton

#import "GTLDashboardAPIConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeDashboardAPIUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
