/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPITimeStamp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPITimeStamp (0 custom class methods, 2 custom properties)

#import "GTLDashboardAPITimeStamp.h"

#import "GTLDashboardAPIDate.h"
#import "GTLDashboardAPITime.h"

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPITimeStamp
//

@implementation GTLDashboardAPITimeStamp
@dynamic date, time;
@end
