/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPITrailListResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPITrailListResponse (0 custom class methods, 2 custom properties)

#import "GTLDashboardAPITrailListResponse.h"

#import "GTLDashboardAPITrailDetails.h"

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPITrailListResponse
//

@implementation GTLDashboardAPITrailListResponse
@dynamic cursor, trails;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"trails" : [GTLDashboardAPITrailDetails class]
  };
  return map;
}

@end
