/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPIQuestionnaireWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPIQuestionnaireWrapper (0 custom class methods, 9 custom properties)

#import "GTLDashboardAPIQuestionnaireWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPIQuestionnaireWrapper
//

@implementation GTLDashboardAPIQuestionnaireWrapper
@dynamic fullness, notes, rating, security, state, timeTaken, trailId,
         transitRegulation, transportType;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"security" : [NSNumber class],
    @"state" : [NSNumber class],
    @"transitRegulation" : [NSNumber class]
  };
  return map;
}

@end
