/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDashboardAPITrailDetailsCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLDashboardAPITrailDetailsCollection (0 custom class methods, 1 custom properties)

#import "GTLDashboardAPITrailDetailsCollection.h"

#import "GTLDashboardAPITrailDetails.h"

// ----------------------------------------------------------------------------
//
//   GTLDashboardAPITrailDetailsCollection
//

@implementation GTLDashboardAPITrailDetailsCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLDashboardAPITrailDetails class]
                                forKey:@"items"];
  return map;
}

@end
