/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryDashboardAPI.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLQueryDashboardAPI (10 custom class methods, 4 custom properties)

#import "GTLQueryDashboardAPI.h"

#import "GTLDashboardAPIAreaWrapper.h"
#import "GTLDashboardAPICursorParameter.h"
#import "GTLDashboardAPISearchByKeywordParameter.h"
#import "GTLDashboardAPITrailDetails.h"
#import "GTLDashboardAPITrailDetailsCollection.h"
#import "GTLDashboardAPITrailListResponse.h"
#import "GTLDashboardAPITrailPointsRequestParameter.h"
#import "GTLDashboardAPITrailPointsResult.h"

@implementation GTLQueryDashboardAPI

@dynamic fields, password, trailId, trailIds;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryDashboardAPI object.

+ (id)queryForGetAllGtfsTrailsWithObject:(GTLDashboardAPICursorParameter *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"dashboardAPI.getAllGtfsTrails";
  GTLQueryDashboardAPI *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLDashboardAPITrailListResponse class];
  return query;
}

+ (id)queryForGetAllTrailsWithObject:(GTLDashboardAPICursorParameter *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"dashboardAPI.getAllTrails";
  GTLQueryDashboardAPI *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLDashboardAPITrailListResponse class];
  return query;
}

+ (id)queryForGetAllValidTrailsWithObject:(GTLDashboardAPICursorParameter *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"dashboardAPI.getAllValidTrails";
  GTLQueryDashboardAPI *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLDashboardAPITrailListResponse class];
  return query;
}

+ (id)queryForGetTrailDetailsWithTrailId:(long long)trailId {
  NSString *methodName = @"dashboardAPI.getTrailDetails";
  GTLQueryDashboardAPI *query = [self queryWithMethodName:methodName];
  query.trailId = trailId;
  query.expectedObjectClass = [GTLDashboardAPITrailDetails class];
  return query;
}

+ (id)queryForGetTrailRawPointsWithObject:(GTLDashboardAPITrailPointsRequestParameter *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"dashboardAPI.getTrailRawPoints";
  GTLQueryDashboardAPI *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLDashboardAPITrailPointsResult class];
  return query;
}

+ (id)queryForGetTrailsByStationNameWithObject:(GTLDashboardAPISearchByKeywordParameter *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"dashboardAPI.getTrailsByStationName";
  GTLQueryDashboardAPI *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLDashboardAPITrailDetailsCollection class];
  return query;
}

+ (id)queryForGetTrailSnappedPointsWithObject:(GTLDashboardAPITrailPointsRequestParameter *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"dashboardAPI.getTrailSnappedPoints";
  GTLQueryDashboardAPI *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLDashboardAPITrailPointsResult class];
  return query;
}

+ (id)queryForRegisterGtfsFullTaskWithPassword:(NSString *)password {
  NSString *methodName = @"dashboardAPI.registerGtfsFullTask";
  GTLQueryDashboardAPI *query = [self queryWithMethodName:methodName];
  query.password = password;
  return query;
}

+ (id)queryForRegisterGtfsTaskWithPassword:(NSString *)password
                                  trailIds:(NSString *)trailIds {
  NSString *methodName = @"dashboardAPI.registerGtfsTask";
  GTLQueryDashboardAPI *query = [self queryWithMethodName:methodName];
  query.password = password;
  query.trailIds = trailIds;
  return query;
}

+ (id)queryForTrailsNearPointWithObject:(GTLDashboardAPIAreaWrapper *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"dashboardAPI.trailsNearPoint";
  GTLQueryDashboardAPI *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLDashboardAPITrailDetailsCollection class];
  return query;
}

@end
