/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryDashboardAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLQueryDashboardAPI (14 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLDashboardAPIAreaWrapper;
@class GTLDashboardAPICursorParameter;
@class GTLDashboardAPIQuestionnaireWrapper;
@class GTLDashboardAPIRouteStatsParameter;
@class GTLDashboardAPISearchByKeywordParameter;
@class GTLDashboardAPITrailPointsRequestParameter;

@interface GTLQueryDashboardAPI : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, assign) long long identifier;
@property (nonatomic, copy) NSString *password;
@property (nonatomic, assign) long long trailId;
@property (nonatomic, copy) NSString *trailIds;

#pragma mark - Service level methods
// These create a GTLQueryDashboardAPI object.

// Method: dashboardAPI.getAllGtfsTrails
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailListResponse.
+ (instancetype)queryForGetAllGtfsTrailsWithObject:(GTLDashboardAPICursorParameter *)object;

// Method: dashboardAPI.getAllStats
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPIRouteStatsResponse.
+ (instancetype)queryForGetAllStatsWithObject:(GTLDashboardAPIRouteStatsParameter *)object;

// Method: dashboardAPI.getAllTrails
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailListResponse.
+ (instancetype)queryForGetAllTrailsWithObject:(GTLDashboardAPICursorParameter *)object;

// Method: dashboardAPI.getAllValidTrails
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailListResponse.
+ (instancetype)queryForGetAllValidTrailsWithObject:(GTLDashboardAPICursorParameter *)object;

// Method: dashboardAPI.getQuestionnaire
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPIQuestionnaireWrapper.
+ (instancetype)queryForGetQuestionnaireWithIdentifier:(long long)identifier;

// Method: dashboardAPI.getStats
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPIRouteStatsWrapper.
+ (instancetype)queryForGetStatsWithTrailId:(long long)trailId;

// Method: dashboardAPI.getTrailDetails
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailDetails.
+ (instancetype)queryForGetTrailDetailsWithTrailId:(long long)trailId;

// Method: dashboardAPI.getTrailRawPoints
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailPointsResult.
+ (instancetype)queryForGetTrailRawPointsWithObject:(GTLDashboardAPITrailPointsRequestParameter *)object;

// Method: dashboardAPI.getTrailsByStationName
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailDetailsCollection.
+ (instancetype)queryForGetTrailsByStationNameWithObject:(GTLDashboardAPISearchByKeywordParameter *)object;

// Method: dashboardAPI.getTrailSnappedPoints
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailPointsResult.
+ (instancetype)queryForGetTrailSnappedPointsWithObject:(GTLDashboardAPITrailPointsRequestParameter *)object;

// Method: dashboardAPI.registerGtfsFullTask
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
+ (instancetype)queryForRegisterGtfsFullTaskWithPassword:(NSString *)password;

// Method: dashboardAPI.registerGtfsTask
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
+ (instancetype)queryForRegisterGtfsTaskWithPassword:(NSString *)password
                                            trailIds:(NSString *)trailIds;

// Method: dashboardAPI.registerQuestionnaire
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
+ (instancetype)queryForRegisterQuestionnaireWithObject:(GTLDashboardAPIQuestionnaireWrapper *)object;

// Method: dashboardAPI.trailsNearPoint
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailDetailsCollection.
+ (instancetype)queryForTrailsNearPointWithObject:(GTLDashboardAPIAreaWrapper *)object;

@end
