/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryDashboardAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLQueryDashboardAPI (10 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLDashboardAPIAreaWrapper;
@class GTLDashboardAPICursorParameter;
@class GTLDashboardAPISearchByKeywordParameter;
@class GTLDashboardAPITrailPointsRequestParameter;

@interface GTLQueryDashboardAPI : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *password;
@property (assign) long long trailId;
@property (copy) NSString *trailIds;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryDashboardAPI object.

// Method: dashboardAPI.getAllGtfsTrails
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailListResponse.
+ (id)queryForGetAllGtfsTrailsWithObject:(GTLDashboardAPICursorParameter *)object;

// Method: dashboardAPI.getAllTrails
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailListResponse.
+ (id)queryForGetAllTrailsWithObject:(GTLDashboardAPICursorParameter *)object;

// Method: dashboardAPI.getAllValidTrails
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailListResponse.
+ (id)queryForGetAllValidTrailsWithObject:(GTLDashboardAPICursorParameter *)object;

// Method: dashboardAPI.getTrailDetails
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailDetails.
+ (id)queryForGetTrailDetailsWithTrailId:(long long)trailId;

// Method: dashboardAPI.getTrailRawPoints
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailPointsResult.
+ (id)queryForGetTrailRawPointsWithObject:(GTLDashboardAPITrailPointsRequestParameter *)object;

// Method: dashboardAPI.getTrailsByStationName
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailDetailsCollection.
+ (id)queryForGetTrailsByStationNameWithObject:(GTLDashboardAPISearchByKeywordParameter *)object;

// Method: dashboardAPI.getTrailSnappedPoints
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailPointsResult.
+ (id)queryForGetTrailSnappedPointsWithObject:(GTLDashboardAPITrailPointsRequestParameter *)object;

// Method: dashboardAPI.registerGtfsFullTask
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
+ (id)queryForRegisterGtfsFullTaskWithPassword:(NSString *)password;

// Method: dashboardAPI.registerGtfsTask
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
+ (id)queryForRegisterGtfsTaskWithPassword:(NSString *)password
                                  trailIds:(NSString *)trailIds;

// Method: dashboardAPI.trailsNearPoint
//  Authorization scope(s):
//   kGTLAuthScopeDashboardAPIUserinfoEmail
// Fetches a GTLDashboardAPITrailDetailsCollection.
+ (id)queryForTrailsNearPointWithObject:(GTLDashboardAPIAreaWrapper *)object;

@end
