/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLServiceDashboardAPI.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Dashboard API (dashboardAPI/v1)
// Description:
//   This API exposes the services required by the mapaton dashboard of mapaton
// Classes:
//   GTLServiceDashboardAPI (0 custom class methods, 0 custom properties)

#import "GTLDashboardAPI.h"

@implementation GTLServiceDashboardAPI

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = @[
    [GTLQueryDashboardAPI class],
    [GTLDashboardAPIAreaWrapper class],
    [GTLDashboardAPICursorParameter class],
    [GTLDashboardAPIDate class],
    [GTLDashboardAPIGPSLocation class],
    [GTLDashboardAPIQuestionnaireWrapper class],
    [GTLDashboardAPIRouteStatsParameter class],
    [GTLDashboardAPIRouteStatsResponse class],
    [GTLDashboardAPIRouteStatsWrapper class],
    [GTLDashboardAPISearchByKeywordParameter class],
    [GTLDashboardAPITime class],
    [GTLDashboardAPITimeStamp class],
    [GTLDashboardAPITrailDetails class],
    [GTLDashboardAPITrailDetailsCollection class],
    [GTLDashboardAPITrailListResponse class],
    [GTLDashboardAPITrailPointsRequestParameter class],
    [GTLDashboardAPITrailPointsResult class],
    [GTLDashboardAPITrailPointWrapper class]
  ];
  return classes;
}
#endif  // DEBUG

- (instancetype)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://mapathon-1337.appspot.com/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
